### ISSUE TITLE
A0221AT version sensor

### ISSUE THREAD

**Issue by MK7GolfR** [lspr98/profitec-go-waterlevel-shottimer#1]
I received a sensor version A0221AT which seems to be slightly different and am getting no signal output from it.  Digging a little I found that  "This sensor is an A0221AT, which is actually a serial controled DYP-A02T. This modules requires a positive pulse on its RX pin to start measuring. About 60ms later it will then proved the measurement on its TX pin."   Does your code send this pulse to start measuring? or can it be made compatible?

**Comment by lspr98** [comment]
Hey,

no, the code does not send this pulse as the sensor variant listed in the BOM does not require it. If you want to send a high pulse during sensor initialization you can adapt the init function in [src/levelsensor.cpp](https://github.com/lspr98/profitec-go-waterlevel-shottimer/blob/main/src/levelsensor.cpp) as follows:

```
void init() {
        // Send HIGH pulse for 60ms to levelsensor
        gpio_set_dir(PIN_LEVELSENSOR_TX, 1);
        gpio_put(PIN_LEVELSENSOR_TX, 1);
        sleep_ms(60);
        gpio_put(PIN_LEVELSENSOR_TX, 0);
        // Route HW UART1 to given RX,TX pins.
        gpio_set_function(PIN_LEVELSENSOR_TX, GPIO_FUNC_UART);
        gpio_set_function(PIN_LEVELSENSOR_RX, GPIO_FUNC_UART);
}
```

I couldn't find a datasheet for the "A0221AT" nor an entry in the DFRobot wiki, so I am assuming a 60ms HIGH pulse is sufficient based on your question. Also, I don't have your sensor to test anything, so I can't guarantee that this will work. After adapting the code, you need to reflash it via USB. 

You could also double check that the TX pin of the display unit is connected to the RX pin of the level sensor and the RX pin of the display unit is connected to the TX pin of the level sensor. Does the display unit show an orange ring as depicted in the manual?

**Comment by MK7GolfR** [comment]
Thanks for the reply, the display still shows the orange ring when connected and I tried swapping the Tx / Rx pins back and forth with no success.  I suspect [this sensor from Amazon ](https://www.amazon.ca/gp/product/B0CFFTS71Y/)must be slightly different and require the pulse to get it started.  I will try to adapt the code and retry, thanks for your help!

**Comment by MK7GolfR** [comment]
I tried adding your adaptions but so far no success unfortunately.
I was able to find some more info regarding this module and it's quirks:

> The only clue to how it worked was "controlled", so was pretty sure auto output, pwm output, switch output, and RS485 output that you'd find in the AO2 family weren't going to work. Fortunately, as advertised, "controlled output" worked just fine with:
> 
> UART: 8 data bits, 1 stop bit, no parity, 9600 bps
> 
> As a regular AO2 response can take around 60 ms, I figured the polling period should be > 70 ms. But for my testing rather than asynchronous went with synchronous. Usually you have to leave some delay for the receiver to stop "ringing".
> 
> In controlled output, when the RX pin sees a falling edge it triggers an ultrasonic pulse. So, you can transmit any byte to the RX pin and it should fire up.
> 
> Four bytes were returned and it worked as you'd expect from the AO2 family: start bit (e.g., 0xff), Data High (e.g., 0x07), Data Low (e.g., 0xa1), CheckSum (e.g., 0xA7)
> Check Sum = (start bit + data high + data low) & 0xff
> Raw Distance = 256 * Data High + Data Low = 1953 mm
> 
> Note: Raw distance is approximate and probably good enough as the unit has temperature compensation (not tested by me). But to get repeatable super-precise distances you’d probably need a function that included temperature, barometric pressure, and humidity as they all impact the speed of sound; but probably not by much so minimal gains.
> 
> In my testing, the system used 3.3V and a "\n" was sent (TX to RX). uart_read_bytes was programmed to wait 100 ms for the test to complete and the data to arrive. My non-precision testing consisted of me moving my hand over it and verifying the range went up with my hand moving away and going down as my hand moved down. Except for initially picking the ESP's uart1's default pin 18 (it startled me as it was also the PWM pin for the board's ultrabright LED and I quickly switched to another pin ; -) the programming went smoothly with no issues

**Comment by lspr98** [comment]
Hey,

thanks for the additional information. If I interpret that correctly, the distance measurement for your sensor version has to be actively triggered. To set the UART data format as described in your answer, another adjustment in the init function in [src/levelsensor.cpp](https://github.com/lspr98/profitec-go-waterlevel-shottimer/blob/main/src/levelsensor.cpp) is required:

```
void init() {
        // 8 data bits, one stop bit and no parity
        uart_set_format(uart1, 8, 1, UART_PARITY_NONE);
        // Send HIGH pulse for 60ms to levelsensor
        gpio_set_dir(PIN_LEVELSENSOR_TX, 1);
        gpio_put(PIN_LEVELSENSOR_TX, 1);
        sleep_ms(60);
        gpio_put(PIN_LEVELSENSOR_TX, 0);
        // Route HW UART1 to given RX,TX pins.
        gpio_set_function(PIN_LEVELSENSOR_TX, GPIO_FUNC_UART);
        gpio_set_function(PIN_LEVELSENSOR_RX, GPIO_FUNC_UART);
}
```

Next, you need to adjust the for loop in the getDistance function, also in [src/levelsensor.cpp](https://github.com/lspr98/profitec-go-waterlevel-shottimer/blob/main/src/levelsensor.cpp) to send something over UART to trigger a measurement:

```
// Try to read a valid value LEVEL_N_RETRY times
for(uint16_t i=0; i<LEVEL_N_RETRY; i++) {

    // Send something to trigger falling edge on sensor RX
    uart_putc(uart1, '\n');
    
    // 100 ms timeout to wait for sensor response
    sleep_ms(100);

    // Recieved no new data. Retry by continuing with next loop
    if(!uart_is_readable(uart1)) {
        continue;
    }
    
    // New data was recieved. According to the sensor wiki, there should be 4 bytes.
    // https://wiki.dfrobot.com/_A02YYUW_Waterproof_Ultrasonic_Sensor_SKU_SEN0311
    uart_read_blocking(uart1, serialData, 4);

    // Check if header byte is correct
    if(serialData[0]==0xff) {
        // Calculate checksum
        int checksum = (serialData[0]+serialData[1]+serialData[2])&0x00FF;
        // Check if checksum matches
        if(checksum == serialData[3]) {
            // Clip distance to [minDistanceMM, maxDistanceMM] range
            float distance = (serialData[1]<<8)+serialData[2];
            if(distance > LEVEL_MAX_DIST_MM) {
                distance = LEVEL_MAX_DIST_MM;
            } else if(distance < LEVEL_MIN_DIST_MM){
                distance = LEVEL_MIN_DIST_MM;
            }
            // Close uart
            uart_deinit(uart1);
            return distance;
        }
    }
}
```

In the snippet above, **uart_putc** sends a newline character to the levelsensor via UART as described in your answer and **sleep_ms** waits 100ms for the sensor to respond. Also, if you happen to find a datasheet for your sensor version, let me know.

**Comment by MK7GolfR** [comment]
Success!
The code adaptions worked perfectly and the sensor now reports back the level.
I wasn't able to find a Datasheet but luckily the info provided from these other buyers proved useful.

**Comment by lspr98** [comment]
Glad to hear that :). If that solved your problem, please feel free to close the issue.
