### ISSUE TITLE
Waveshare RP2040 - LCD 0.99

### ISSUE THREAD

**Issue by CoderX40** [lspr98/profitec-go-waterlevel-shottimer#2]
Hi there!

I've got a WaveShare RP2040 LCD 0.99B about that I wanted to use for this project: https://www.waveshare.com/wiki/RP2040-LCD-0.99-B

Main reason was to try out a more 'foolproof' way of building this mod for people who can understand the build, but not want to 3D print, solder pins together, etc. I thought this might be good alternative to the original idea.

I tested out the code, it builds and flashes correctly onto the board, but I'm just getting a white/wavy screen on the RP2040. From what I can see, the RP2040 you used initially in your build appears to be pretty identical to the one I've got (main difference is the size) but I'm not seeing any obvious reasons throughout the whole code why it displays a white screen rather than the orange circle/timer.

From what I can see, it does go onto the board correctly - as if I leave it for a few seconds it turns off, then wakes upon movement.

Any chance you can think of a reason why your code wouldn't be suitable for this board? I've looked at the connections, pins, colours etc but couldn't find anything obvious. Any help would be amazing thanks!

**Comment by CoderX40** [comment]
Nevermind! I missed a pin that was different from your original build - I've more or less accounted for the different screensize etc so just moving the ring to the centre. Will post a copy of the modified sections if anyone else wants a copy

**Comment by mintyman** [comment]
> Nevermind! I missed a pin that was different from your original build - I've more or less accounted for the different screensize etc so just moving the ring to the centre. Will post a copy of the modified sections if anyone else wants a copy

I'm interested in going down the route of RP2040-LCD-0.99-B to limit soldering etc. Can you provide more details on changes to the code / build ?
